# workflows/hello-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
  namespace: argo
spec:
  entrypoint: whalesay3
  templates:
    - name: whalesay3
      container:
        image: docker/subtle-notify:latest
        command: [cowsay3]
        args: ["hello from argo workflows"]
