# workflows/hello-template.yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-template
  namespace: argo
spec:
  entrypoint: whalesay2
  templates:
    - name: whalesay2
      container:
        image: docker/whalesay2:latest
        command: [cowsay2]
        args: ["hello from argo workflows"]
